LeagueApp/LeagueApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from user import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^user/', include('user.urls'), name='user'),
    url(r'^admin/', admin.site.urls),
]

LeagueApp/user/urls.py
from django.conf.urls import url

from . import views

app_name = 'user'
urlpatterns = [url(r'^$', views.handle_user, name='user'),
               url(r"^(?P<username>[\S .'-]+)/results/", views.results, name='results')]

LeagueApp/user/models.py
from __future__ import unicode_literals
import json
from django.db import models
from user.util import process_summoner


class User(models.Model):
    name = models.CharField(max_length=50, default="defaultname")
    verbose_name = models.CharField(max_length=50, default="defaultname")
    rank = models.CharField(max_length=50, default="defaultrank")
    date_accessed = models.DateField(auto_now=True)
    top_5_champs = models.CharField(max_length=300, null=True)
    top_5_played = models.CharField(max_length=300, null=True)
    recommended_champs = models.CharField(max_length=300, null=True)
    champion_vector = models.CharField(max_length=300, null=True)
    summoner_icon = models.CharField(max_length=200, default="none")

    def set_top_5(self, listOf5Champs):
        self.top_5_champs = json.dumps(listOf5Champs)
        self.save()

    def set_top_5_played(self, listOf5Champs):
        self.top_5_played = json.dumps(listOf5Champs)
        self.save()

    def set_recommended_champs(self, listOfRecChamps):
        self.recommended_champs = json.dumps(listOfRecChamps)
        self.save()

    def set_champion_vector(self, vector):
        self.champion_vector = json.dumps(vector)
        self.save()

    def get_top_5(self):
        return json.loads(self.top_5_champs)

    def get_top_5_played(self):
        return json.loads(self.top_5_played)

    def get_recommended_champs(self):
        return json.loads(self.recommended_champs)

    def process(self):
        top5played, recs, self.summoner_icon, self.rank = process_summoner(self.name)
        self.set_top_5_played(top5played)
        self.set_recommended_champs(recs)

    def __str__(self):
        return self.name


def clear_cache():
    User.objects.all().delete()

LeagueApp/user/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.forms import Form

from user import models


# class ResultsView(generic.DetailView):
#     object = models.User
#     template_name = 'user/results.html'
#     context_object_name = 'user'

def results(request, username):
    user = get_object_or_404(models.User, name=username)
    return render(request, 'user/results.html', {'user': user,
                                                 'recommended_champs': user.get_recommended_champs(),
                                                 'top5_champs': user.get_top_5_played()})


def home(request):
    return render(request, 'home/home.html')


def handle_user(request):
    form = Form(request.POST)
    verboseName = request.POST['username']
    name = verboseName.replace(" ", "")
    if verboseName == '':
        return render(request, 'home/home.html', {
            'error_message': "Type in your summoner name!"
        })

    if not models.User.objects.filter(name=name).exists():
        curr_user = models.User(name=name, verbose_name=verboseName.capitalize())
        curr_user.process()
        curr_user.save()

    return HttpResponseRedirect(reverse('user:results', args=(name,)))

LeagueApp/user/templates/home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <center><h1>Find new champions to play :^)</h1></center>
    {% load static %}
    <center><img src="{% static 'Home/lol_logo.png' %}" alt="LOL logo"/></center>

    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %}

    <form action="{% url 'user:user' %}" method="post">
        {% csrf_token %}
        <input type="text" class="form-control input-lg" placeholder="Summoner Name" name="username"/>
        <center><input type="submit" id="go"/></center>
    </form>
</body>
</html>

LeagueApp/user/templates/user/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <h3>Here are your results: {{ user.verbose_name }}</h3>
    <h4>{{ user.rank }}</h4>
    <img src="{{ user.summoner_icon }}" alt="Summoner Icon"/>
    <h5>Here are your most played champions: </h5>
    <ul>
        {% for champ in top5_champs %}
        <li>{{forloop.counter}} : {{champ}}</li>
        <br />
        {% endfor %}
    </ul>
    <h5>Here are your recommendations: </h5>
    <ul>
        {% for champ in recommended_champs %}
        <li>{{forloop.counter}} : {{champ}}</li>
        <br />
        {% endfor %}
    </ul>
</body>
</html>